-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrEm/zI8falJwlL1S
qMmGmAo3FQJaslDOLsCVvRWYg6ygCgYIKoZIzj0DAQehRANCAAQEd2VNmyJJAraM
9PBxPwVG/jb4O/U38MXjHpIYf76Kq8TPZS1MWyOmJBd4IntFj3PpA7jaSL6nC7Qs
5aJ1hocj
-----END PRIVATE KEY-----